function [fitresult, yFit, ci, gof] = FitGaussian(x, y)
%FitGaussian(X,Y)
%  Fit a Gaussian curve with x0=0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Sep-2015 10:45:04

try

[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '1-a*exp(-(x)^2/s)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.5 5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

yFit = feval(fitresult,xData);
ci = confint(fitresult);

catch
    
    fitresult = struct('a',nan,'s',nan,'x0',nan,'c',nan);
    yFit = zeros(size(yData));
    ci = zeros(2,2);
    FeedbackMessage('GarvanFrap','Could not fit gaussian curve','Warning')
    
end
