function [tau, g0, g_inf, fitresult, gof] = FitTemporalCorrelation(t, rt1)
%CREATEFIT(T,RT1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: rt1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jan-2018 15:04:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, rt1 );

% Set up fittype and options.
ft = fittype( 'A/(1+(x/b1))+C', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [max(yData) 0.01 400];
opts.Lower = [0 0 0];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

tau = fitresult.b1;
g0 = fitresult.A;
g_inf = fitresult.C;

%{
% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'rt1 vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t
ylabel rt1
grid on
%}

